language: node_js
node_js:
  - "10.16.3"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages

  skip_cleanup: true
  github_token: 08af5300a4ee15fbcaab3a192ff60cd30168de0f #Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master