language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $2rQyGzkMaOo67ROsawhi2A # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master